

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."cart_items" (
    "cart_id" integer NOT NULL,
    "item_sku" "text" NOT NULL,
    "quantity" integer,
    "price" integer,
    "customer_name" "text",
    "timestamp" timestamp with time zone DEFAULT "now"(),
    "line_item_id" integer DEFAULT 0 NOT NULL,
    "id" integer
);


ALTER TABLE "public"."cart_items" OWNER TO "postgres";


ALTER TABLE "public"."cart_items" ALTER COLUMN "cart_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."cart_inventory_cart_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."carts" (
    "cart_id" integer NOT NULL,
    "timestamp" timestamp with time zone DEFAULT "now"() NOT NULL,
    "customer_name" "text"
);


ALTER TABLE "public"."carts" OWNER TO "postgres";


ALTER TABLE "public"."carts" ALTER COLUMN "cart_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."carts_cart_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."global_inventory" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "num_green_potions" integer,
    "num_green_ml" integer,
    "gold" integer,
    "num_red_potions" integer DEFAULT 0,
    "num_red_ml" integer DEFAULT 0,
    "num_blue_potions" integer DEFAULT 0,
    "num_blue_ml" integer DEFAULT 0,
    "num_purple_potions" integer DEFAULT 0,
    "num_purple_ml" integer DEFAULT 0,
    "num_yellow_potions" integer DEFAULT 0,
    "num_yellow_ml" integer DEFAULT 0,
    "num_dark_potions" integer DEFAULT 0,
    "num_dark_ml" integer DEFAULT 0,
    "sku" "text"
);


ALTER TABLE "public"."global_inventory" OWNER TO "postgres";


ALTER TABLE "public"."global_inventory" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."global_inventory_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."potion_catalog" (
    "sku" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "num_red_ml" integer DEFAULT 0,
    "num_green_ml" integer DEFAULT 0,
    "num_blue_ml" integer DEFAULT 0,
    "num_dark_ml" integer DEFAULT 0,
    "price" integer DEFAULT 20,
    "quantity" integer DEFAULT 0,
    "gold" integer DEFAULT 100
);


ALTER TABLE "public"."potion_catalog" OWNER TO "postgres";


ALTER TABLE ONLY "public"."carts"
    ADD CONSTRAINT "carts_pkey" PRIMARY KEY ("cart_id");



ALTER TABLE ONLY "public"."global_inventory"
    ADD CONSTRAINT "global_inventory_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."potion_catalog"
    ADD CONSTRAINT "potion_catalog_pkey" PRIMARY KEY ("sku");



ALTER TABLE "public"."cart_items" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."carts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."global_inventory" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."potion_catalog" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."global_inventory";



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";


















































































































































































































GRANT ALL ON TABLE "public"."cart_items" TO "anon";
GRANT ALL ON TABLE "public"."cart_items" TO "authenticated";
GRANT ALL ON TABLE "public"."cart_items" TO "service_role";



GRANT ALL ON SEQUENCE "public"."cart_inventory_cart_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."cart_inventory_cart_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."cart_inventory_cart_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."carts" TO "anon";
GRANT ALL ON TABLE "public"."carts" TO "authenticated";
GRANT ALL ON TABLE "public"."carts" TO "service_role";



GRANT ALL ON SEQUENCE "public"."carts_cart_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."carts_cart_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."carts_cart_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."global_inventory" TO "anon";
GRANT ALL ON TABLE "public"."global_inventory" TO "authenticated";
GRANT ALL ON TABLE "public"."global_inventory" TO "service_role";



GRANT ALL ON SEQUENCE "public"."global_inventory_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."global_inventory_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."global_inventory_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."potion_catalog" TO "anon";
GRANT ALL ON TABLE "public"."potion_catalog" TO "authenticated";
GRANT ALL ON TABLE "public"."potion_catalog" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
